# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      core:
        patterns:
          - pyperclip
          - yt-dlp
          - ffmpeg
          - ffprobe
      development:
        patterns:
          - pyinstaller
          - pre-commit

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
