# .github/release.yml

changelog:
  categories:
    - title: Major Changes
      labels:
        - enhancement
    - title: Minor Changes
      labels:
        - refactor
        - documentation
    - title: Bugfixes
      labels:
        - bug
    - title: Dependency Updates
      labels:
        - dependencies
    - title: Other
      labels:
        - "*"
