name: Label Pre-commit PRs

on:
  pull_request:
    types: opened

jobs:
  label-precommit-prs:
    runs-on: ubuntu-latest

    steps:
    - name: Label PRs from pre-commit-ci[bot]
      if: github.actor == 'pre-commit-ci[bot]'
      uses: actions-ecosystem/action-add-labels@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        labels: dependencies
